src/Entity/Question.php
<?php

namespace App\Entity;

use App\Repository\QuestionRepository;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass=QuestionRepository::class)
 */
class Question
{
    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     * @Gedmo\Slug(fields={"name"})
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $question;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $askedAt;

    /**
     * @ORM\Column(type="integer")
     */
    private $votes = 0;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getQuestion(): ?string
    {
        return $this->question;
    }

    public function setQuestion(string $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function getAskedAt(): ?DateTimeInterface
    {
        return $this->askedAt;
    }

    public function setAskedAt(?DateTimeInterface $askedAt): self
    {
        $this->askedAt = $askedAt;

        return $this;
    }

    public function getVotesString(): string
    {
        $prefix = $this->getVotes() >= 0 ? '+' : '-';

        return sprintf('%s %d', $prefix, abs($this->getVotes()));
    }

    public function getVotes(): int
    {
        return $this->votes;
    }

    public function setVotes(int $votes): self
    {
        $this->votes = $votes;

        return $this;
    }

    public function upVote(): self
    {
        $this->votes++;

        return $this;
    }

    public function downVote(): self
    {
        $this->votes--;

        return $this;
    }
}

src/Controller/CommentController.php
<?php


namespace App\Controller;


use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;

class CommentController extends AbstractController
{
    /**
     * @Route("/comments/{id}/vote/{direction<up|down>}", methods={"POST"})
     * @param $id
     * @param $direction
     * @param LoggerInterface $logger
     * @return JsonResponse
     */
    public function commentVote($id, $direction, LoggerInterface $logger)
    {
        // todo use id to query database

        // use real logic here to save this to the database
        if ($direction === 'up') {
            $logger->info('voting up');
            $currentVoteCount = rand(7, 100);
        } else {
            $logger->info('voting down');
            $currentVoteCount = rand(0, 5);
        }

        return $this->json(['votes' => $currentVoteCount]);
    }
}

src/Controller/QuestionController.php
<?php


namespace App\Controller;


use App\Entity\Question;
use App\Repository\QuestionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class QuestionController extends AbstractController
{
    private $logger;
    private $isDebug;

    public function __construct(LoggerInterface $logger, bool $isDebug)
    {
        $this->logger = $logger;
        $this->isDebug = $isDebug;
    }

    /**
     * @Route("/", name="app_homepage")
     * @param QuestionRepository $repository
     * @return Response
     */
    public function homepage(QuestionRepository $repository): Response
    {
        /*
        // Environment $environment add this param
        // fun example for using Twig service directly
        $html = $environment->render('question/homepage.html.twig');

        return new Response($html);
        */

        $questions = $repository->findAllAskedOrderByNewest();

        return $this->render('question/homepage.html.twig', [
            'questions' => $questions
        ]);
    }

    /**
     * @Route("/questions/new", name="app_question_new")
     * @param EntityManagerInterface $entityManager
     * @return Response
     * @throws Exception
     */
    public function new(EntityManagerInterface $entityManager): Response
    {
        return new Response('Sounds like great feature for V2!');
    }

    /**
     * @Route("/questions/{slug}", name="app_question_show")
     * @param Question $question
     * @return Response
     */
    public function show(Question $question): Response
    {
        if ($this->isDebug) {
            $this->logger->info('We are in debug mode!');
        }

        $answers = [
            'Make sure your cat is sitting `purrrfectly` still 🤣',
            'Honestly, I like furry shoes better than MY cat',
            'Maybe... try saying the spell backwards?',
        ];

        return $this->render('question/show.html.twig', [
            'question' => $question,
            'answers' => $answers
        ]);
    }

    /**
     * @Route("/questions/{slug}/vote", name="app_question_vote", methods={"POST"})
     * @param Question $question
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     */
    public function questionVote(Question $question, Request $request, EntityManagerInterface $entityManager)
    {
        $direction = $request->request->get('direction');

        if ($direction === 'up') {
            $question->upVote();
        } else if ($direction === 'down') {
            $question->downVote();
        }

        $entityManager->flush();

        return $this->redirectToRoute('app_question_show', [
            'slug' => $question->getSlug()
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Spartan&display=swap">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">
        {{ encore_entry_link_tags('app') }}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-light bg-light" style="height: 100px;">
    <a class="navbar-brand" href="{{ path('app_homepage') }}">
        <i style="color: #444; font-size: 2rem;" class="pb-1 fad fa-cauldron"></i>
        <p class="pl-2 d-inline font-weight-bold" style="color: #444;">Cauldron Overflow</p>
    </a>
    <button class="btn btn-dark">Sign up</button>
</nav>

{% block body %}{% endblock %}
<footer class="mt-5 p-3 text-center">
    Made with <i style="color: red;" class="fa fa-heart"></i> by the guys and gals at <a style="color: #444; text-decoration: underline;" href="https://symfonycasts.com">SymfonyCasts</a>
</footer>
{% block javascripts %}
    {{ encore_entry_script_tags('app') }}
{% endblock %}
</body>
</html>

templates/question/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="jumbotron-img jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">Your Questions Answered</h1>
            <p class="lead">And even answers for those questions you didn't think to ask!</p>
        </div>
    </div>
    <div class="container">
        <div class="row mb-3">
            <div class="col">
                <button class="btn btn-question">Ask a Question</button>
            </div>
        </div>
        <div class="row">
            {% for question in questions %}
            <div class="col-12">
                <div style="box-shadow: 2px 3px 9px 4px rgba(0,0,0,0.04);">
                    <div class="q-container p-4">
                        <div class="row">
                            <div class="col-2 text-center">
                                <img src="{{ asset('images/tisha.png') }}" width="100" height="100">
                                <div class="d-block mt-3 vote-arrows">
                                    <a class="vote-up" href="#"><i class="far fa-arrow-alt-circle-up"></i></a>
                                    <a class="vote-down" href="#"><i class="far fa-arrow-alt-circle-down"></i></a>
                                </div>
                            </div>
                            <div class="col">
                                <a class="q-title" href="{{ path('app_question_show', {slug: question.slug}) }}"><h2>
                                    {{ question.name }}</h2></a>
                                <div class="q-display p-3">
                                    <i class="fa fa-quote-left mr-3"></i>
                                    <p class="d-inline">{{ question.question|parse_markdown }}</p>
                                    <p class="pt-4"><strong>--Tisha</strong></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <a class="answer-link" href="{{ path('app_question_show', {slug: question.slug}) }}" style="color: #fff;">
                        <p class="q-display-response text-center p-3">
                            <i class="fa fa-magic magic-wand"></i> 6 answers
                        </p>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/question/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Question: {{ question.name }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="my-4">Question</h2>
                <div style="box-shadow: 2px 3px 9px 4px rgba(0,0,0,0.04);">
                    <div class="q-container-show p-4">
                        <div class="row">
                            <div class="col-2 text-center">
                                <img src="{{ asset('images/tisha.png') }}" width="100" height="100">
                                <div class="mt-3">
                                    <small>
                                        {% if question.askedAt %}
                                            Asked <br>
                                            {{ question.askedAt|ago }}
                                        {% else %}
                                            (unpublished)
                                        {% endif %}
                                    </small>
                                    <form action="{{ path('app_question_vote', {slug: question.slug}) }}" method="post">
                                        <div class="vote-arrows vote-arrows-alt flex-fill pt-2" style="min-width: 90px;">
                                            <button class="vote-up btn btn-link" name="direction" value="up"><i class="far fa-arrow-alt-circle-up"></i></button>
                                            <button class="vote-down btn btn-link" name="direction" value="down"><i class="far fa-arrow-alt-circle-down"></i></button>
                                            <span>{{ question.votesString }}</span>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="col">
                                <h1 class="q-title-show">{{ question.name }}</h1>
                                <div class="q-display p-3">
                                    <i class="fa fa-quote-left mr-3"></i>
                                    <p class="d-inline">{{ question.question|parse_markdown }}</p>
                                    <p class="pt-4"><strong>--Tisha</strong></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="d-flex justify-content-between my-4">
            <h2 class="">Answers <span style="font-size:1.2rem;">({{ answers|length }})</span></h2>
            <button class="btn btn-sm btn-secondary">Submit an Answer</button>
        </div>

        <ul class="list-unstyled">
            {% for answer in answers %}
                <li class="mb-4">
                    <div class="d-flex justify-content-center">
                        <div class="mr-2 pt-2">
                            <img src="{{ asset('images/tisha.png') }}" width="50" height="50">
                        </div>
                        <div class="mr-3 pt-2">
                            {{ answer|striptags|parse_markdown }}
                            <p>-- Mallory</p>
                        </div>
                        <div class="vote-arrows flex-fill pt-2 js-vote-arrows" style="min-width: 90px;">
                            <a class="vote-up" href="#" data-direction="up"><i class="far fa-arrow-alt-circle-up"></i></a>
                            <a class="vote-down" href="#" data-direction="down"><i class="far fa-arrow-alt-circle-down"></i></a>
                            <span>+ <span class="js-vote-total">6</span></span>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}